# Generated by Django 3.1.2 on 2023-05-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'BMI 健康指標'},
        ),
        migrations.AlterField(
            model_name='people',
            name='h',
            field=models.IntegerField(verbose_name='身高 (公分)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='pname',
            field=models.CharField(max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='ssn',
            field=models.CharField(max_length=10, verbose_name='身分證字號'),
        ),
        migrations.AlterField(
            model_name='people',
            name='w',
            field=models.IntegerField(verbose_name='體重 (公斤)'),
        ),
    ]
