# Generated by Django 3.1.2 on 2023-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0002_auto_20230523_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='people',
            name='pname',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
