# Generated by Django 3.1.2 on 2023-05-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0003_auto_20230523_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bmi/images/'),
        ),
    ]
