# Generated by Django 3.1.2 on 2023-05-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0004_auto_20230523_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
    ]
