# Generated by Django 3.1.2 on 2023-05-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0005_auto_20230523_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='photo',
        ),
    ]
